name: Launch Scala Steward

# This workflow will launch everyday at 00:00
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: {}

jobs:
  scala-steward:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    name: Launch Scala Steward
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: coursier/cache-action@v6.4.6
        with:
          job: ci
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Launch Scala Steward
        uses: scala-steward-org/scala-steward-action@v2.67.0
        with:
          github-token: ${{ secrets.SCALA_STEWARD_PERSONAL_ACCESS_TOKEN }}
